### ISSUE TITLE
如何部署服务到本地

### ISSUE THREAD

**Issue by SonglinLife** [Yuyz0112/relia#4]
文档上只提到了在cf上部署，因为需要测试本地的一些模型，更需要本地部署服务，期待回复。

**Comment by Yuyz0112** [comment]
@SonglinLife 

可以参考文档 https://github.com/Yuyz0112/relia/blob/main/docs/contributing.zh-CN.md 本地启动。

另外欢迎反馈使用感受和测试结果。
